### ISSUE TITLE
Please document which AMQP version is supported

### ISSUE THREAD

**Issue by jpluimers** [felipecaputo/delphi-amqp#5]
From the <https://github.com/felipecaputo/delphi-amqp/blob/master/README.md> it is not clear which AMQP version is supported.

Can you please document that?

**Comment by felipecaputo** [comment]
Hi @jpluimers  sure, I forgot to update readme.

I'm currently writing to be amqp 0.9.1 with some changes to work well with RabbitMQ and ApolloMQ.

I will also update the protocol documentation I'm using to write the component

**Comment by jpluimers** [comment]
Thanks. Any plans for AMQP 1.0?

**Comment by felipecaputo** [comment]
I was thinking about it but, AMQP 1.0 is a completly new protocol, it changed a lot and most broker in market support 0.9.1. Even RabbitMQ only supports 1.0 via a plugin.

But I can use the same communication engine after finish the 0.9.1.

I'll leave this open to make me fill the Readme.md o/

**Comment by felipecaputo** [comment]
Closed by PR #7

**Comment by jpluimers** [comment]
note that the new sentence in the readme is not finished in https://github.com/felipecaputo/delphi-amqp/commit/07d3a89ddba27644839c156a96c60745eee9bcea

> An AMQP connector for ObjectPascal / Delphi, that targets to implement all AMQP (version 0.9.1) methods of the .
